networks:
  rustdesk:
    driver: bridge
    name: rustdesk
services:
  hbbr:
    command: hbbr
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server
    networks:
      - rustdesk
    ports:
      - 21117:21117
      #- 21119:21119
    restart: unless-stopped
    volumes:
      - ./root:/root
  hbbs:
    command: hbbs
    container_name: rustdesk-hbbs
    depends_on:
      - hbbr
    image: rustdesk/rustdesk-server
    networks:
      - rustdesk
    ports:
      #- 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      #- 21118:21118
    restart: unless-stopped
    volumes:
      - ./root:/root
